name: Docker Image CI

env:
  IMAGE_NAME: dsopbuilder
  
on:
  workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8


      #Security Check - Bandit
      - uses: actions/checkout@v2
      - name: Security check - Bandit
        uses: ioggstream/bandit-report-artifacts@v0.0.2
        with:
          project_path: .
          ignore_failure: true

      - name: Security check report artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Security report
          path: output/security_report.txt
                      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: | 
            shuffereu/bowtie:latest
            shuffereu/bowtie:${{github.run_number}}

  security:
    needs: docker
    runs-on: ubuntu-latest
    steps:
  #Container Scan
      - name: Container Scan
        uses: azure/container-scan@v0
        with:
          image-name: shuffereu/bowtie:latest 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          ignore_failure: true